/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { ChatbotLayout, HubAIModel, HubChatMessage, HubCompassAction } from "./types/types";
export namespace Components {
    interface ArcgisHubIdentity {
        "client": string;
        "portal": string;
        "redirect": string;
    }
    interface HubAibot {
        "apikey": string;
        "chatOpen": boolean;
        "language": string;
        /**
          * Option for Chatbot to be a FAB popup, or a full screen window
         */
        "layout": ChatbotLayout;
        "loadHistory": (channelId?: string) => Promise<void>;
        "model": HubAIModel;
        "modelUrl": string;
        "personality": string;
        "useAI": boolean;
        "welcome": string;
    }
    interface HubChatAction {
        "actionLink": Function;
        "actionTitle": string;
    }
    interface HubChatFab {
    }
    interface HubChatGallery {
    }
    interface HubChatInput {
        "disabled": boolean;
    }
    interface HubChatMap {
        "datasets": string | string[];
        "latitude": number;
        "location": string;
        "longitude": number;
        "zoom": number;
    }
    interface HubChatResponse {
        /**
          * Option to show feedback from AI
         */
        "allowFeedback": boolean;
        /**
          * Message to display If this message is deleted, this will be removed.
         */
        "message": HubChatMessage;
    }
    interface HubCompassHistory {
        "history": HubCompassAction[];
    }
}
export interface HubChatInputCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLHubChatInputElement;
}
declare global {
    interface HTMLArcgisHubIdentityElement extends Components.ArcgisHubIdentity, HTMLStencilElement {
    }
    var HTMLArcgisHubIdentityElement: {
        prototype: HTMLArcgisHubIdentityElement;
        new (): HTMLArcgisHubIdentityElement;
    };
    interface HTMLHubAibotElement extends Components.HubAibot, HTMLStencilElement {
    }
    var HTMLHubAibotElement: {
        prototype: HTMLHubAibotElement;
        new (): HTMLHubAibotElement;
    };
    interface HTMLHubChatActionElement extends Components.HubChatAction, HTMLStencilElement {
    }
    var HTMLHubChatActionElement: {
        prototype: HTMLHubChatActionElement;
        new (): HTMLHubChatActionElement;
    };
    interface HTMLHubChatFabElement extends Components.HubChatFab, HTMLStencilElement {
    }
    var HTMLHubChatFabElement: {
        prototype: HTMLHubChatFabElement;
        new (): HTMLHubChatFabElement;
    };
    interface HTMLHubChatGalleryElement extends Components.HubChatGallery, HTMLStencilElement {
    }
    var HTMLHubChatGalleryElement: {
        prototype: HTMLHubChatGalleryElement;
        new (): HTMLHubChatGalleryElement;
    };
    interface HTMLHubChatInputElement extends Components.HubChatInput, HTMLStencilElement {
    }
    var HTMLHubChatInputElement: {
        prototype: HTMLHubChatInputElement;
        new (): HTMLHubChatInputElement;
    };
    interface HTMLHubChatMapElement extends Components.HubChatMap, HTMLStencilElement {
    }
    var HTMLHubChatMapElement: {
        prototype: HTMLHubChatMapElement;
        new (): HTMLHubChatMapElement;
    };
    interface HTMLHubChatResponseElement extends Components.HubChatResponse, HTMLStencilElement {
    }
    var HTMLHubChatResponseElement: {
        prototype: HTMLHubChatResponseElement;
        new (): HTMLHubChatResponseElement;
    };
    interface HTMLHubCompassHistoryElement extends Components.HubCompassHistory, HTMLStencilElement {
    }
    var HTMLHubCompassHistoryElement: {
        prototype: HTMLHubCompassHistoryElement;
        new (): HTMLHubCompassHistoryElement;
    };
    interface HTMLElementTagNameMap {
        "arcgis-hub-identity": HTMLArcgisHubIdentityElement;
        "hub-aibot": HTMLHubAibotElement;
        "hub-chat-action": HTMLHubChatActionElement;
        "hub-chat-fab": HTMLHubChatFabElement;
        "hub-chat-gallery": HTMLHubChatGalleryElement;
        "hub-chat-input": HTMLHubChatInputElement;
        "hub-chat-map": HTMLHubChatMapElement;
        "hub-chat-response": HTMLHubChatResponseElement;
        "hub-compass-history": HTMLHubCompassHistoryElement;
    }
}
declare namespace LocalJSX {
    interface ArcgisHubIdentity {
        "client"?: string;
        "portal"?: string;
        "redirect"?: string;
    }
    interface HubAibot {
        "apikey"?: string;
        "chatOpen"?: boolean;
        "language"?: string;
        /**
          * Option for Chatbot to be a FAB popup, or a full screen window
         */
        "layout"?: ChatbotLayout;
        "model"?: HubAIModel;
        "modelUrl"?: string;
        "personality"?: string;
        "useAI"?: boolean;
        "welcome"?: string;
    }
    interface HubChatAction {
        "actionLink"?: Function;
        "actionTitle"?: string;
    }
    interface HubChatFab {
    }
    interface HubChatGallery {
    }
    interface HubChatInput {
        "disabled"?: boolean;
        "onHubChatInputEntered"?: (event: HubChatInputCustomEvent<HubChatMessage>) => void;
    }
    interface HubChatMap {
        "datasets"?: string | string[];
        "latitude"?: number;
        "location"?: string;
        "longitude"?: number;
        "zoom"?: number;
    }
    interface HubChatResponse {
        /**
          * Option to show feedback from AI
         */
        "allowFeedback"?: boolean;
        /**
          * Message to display If this message is deleted, this will be removed.
         */
        "message"?: HubChatMessage;
    }
    interface HubCompassHistory {
        "history"?: HubCompassAction[];
    }
    interface IntrinsicElements {
        "arcgis-hub-identity": ArcgisHubIdentity;
        "hub-aibot": HubAibot;
        "hub-chat-action": HubChatAction;
        "hub-chat-fab": HubChatFab;
        "hub-chat-gallery": HubChatGallery;
        "hub-chat-input": HubChatInput;
        "hub-chat-map": HubChatMap;
        "hub-chat-response": HubChatResponse;
        "hub-compass-history": HubCompassHistory;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "arcgis-hub-identity": LocalJSX.ArcgisHubIdentity & JSXBase.HTMLAttributes<HTMLArcgisHubIdentityElement>;
            "hub-aibot": LocalJSX.HubAibot & JSXBase.HTMLAttributes<HTMLHubAibotElement>;
            "hub-chat-action": LocalJSX.HubChatAction & JSXBase.HTMLAttributes<HTMLHubChatActionElement>;
            "hub-chat-fab": LocalJSX.HubChatFab & JSXBase.HTMLAttributes<HTMLHubChatFabElement>;
            "hub-chat-gallery": LocalJSX.HubChatGallery & JSXBase.HTMLAttributes<HTMLHubChatGalleryElement>;
            "hub-chat-input": LocalJSX.HubChatInput & JSXBase.HTMLAttributes<HTMLHubChatInputElement>;
            "hub-chat-map": LocalJSX.HubChatMap & JSXBase.HTMLAttributes<HTMLHubChatMapElement>;
            "hub-chat-response": LocalJSX.HubChatResponse & JSXBase.HTMLAttributes<HTMLHubChatResponseElement>;
            "hub-compass-history": LocalJSX.HubCompassHistory & JSXBase.HTMLAttributes<HTMLHubCompassHistoryElement>;
        }
    }
}
